<?php /* @var $this Zend_View */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $this->title ?></title>
	<script type="text/javascript" src="../js/css_browser_selector.js"></script>
	<style type='text/css'>
		/* Main styles */
		body {
			background:		#4c4c4c;
			font-family:	sans-serif;
			font-size:		12px;
		}
		form {
			background:		#e0dfe3;
			width:			350px;
			margin-left:	-175px;
			height:			180px;
			margin-top:		-90px;
			position:		absolute;
			top:			50%;
			left:			50%;
			border:			4px solid #4271c9;
			border-radius:	4px;
			-webkit-border-radius: 4px;
			-moz-border-radius: 4px;
		}
		dl {
			margin-top:		40px;
		}
		dt {
			float:			left;
			width:			140px;
			text-align:		right;
			display:		none;
		}
		dt label {
			margin-right:	10px;
		}
		dd {
			padding:		0px;
			margin:			0px;
			clear:			right;
			text-align:		center;
		}
		dd, dt {
			height:			30px;
			line-height:	26px;
			margin-bottom:	8px;
		}
		input#username, input#password {
			width:			160px;
			border:			1px solid #a5acb2;
		}
		input#login {
			width:			auto;
			padding:		4px 8px;
			margin-top:		30px;
			margin-right:	10px;
		}
		dd#login-element {
			text-align:		right;
		}
		/* Mobile styles */
		.mobile form {
			height:			100%;
			width:			100%;
			margin:			0;
			top:			0;
			left:			0;
			position:		relative;
		}
		.mobile dd {
			height:			auto;
		}
		.mobile dd {
			margin-bottom:	40px;
		}
		.mobile input {
			font-size:		34px;
			vertical-align: middle;
		}
		.mobile input#username, .mobile input#password {
			width:			50%;
			height:			60px;
		}
		.mobile input#login {
			width:			130px;
			margin:			0;
			padding:		8px 0;
		}
		.mobile dd#login-element {
			text-align:		center;
		}
	</style>
	<!--[if IE]>
	<style type='text/css'>
		dt {
			display:		block;
		}
		dd {
			text-align:		left;
		}
	</style>
	<![endif]-->
</head>
<body>
	<?php echo $this->form ?>
</body>
</html>